/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scrlib_ScrLib */

#ifndef _Included_scrlib_ScrLib
#define _Included_scrlib_ScrLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scrlib_ScrLib
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_scrlib_ScrLib_init
  (JNIEnv *, jclass);

/*
 * Class:     scrlib_ScrLib
 * Method:    endwin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_scrlib_ScrLib_endwin
  (JNIEnv *, jclass);

/*
 * Class:     scrlib_ScrLib
 * Method:    mvprint
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_scrlib_ScrLib_mvprint
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     scrlib_ScrLib
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_scrlib_ScrLib_clear
  (JNIEnv *, jclass);

/*
 * Class:     scrlib_ScrLib
 * Method:    getch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_scrlib_ScrLib_getch
  (JNIEnv *, jclass);

/*
 * Class:     scrlib_ScrLib
 * Method:    refresh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_scrlib_ScrLib_refresh
  (JNIEnv *, jclass);

/*
 * Class:     scrlib_ScrLib
 * Method:    scrWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_scrlib_ScrLib_scrWidth
  (JNIEnv *, jclass);

/*
 * Class:     scrlib_ScrLib
 * Method:    scrHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_scrlib_ScrLib_scrHeight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
